---
# http://bosh.io/docs/warden-cpi.html#cloud-config
name: storer

director_uuid: DIRECTOR_UUID

releases:
- name: syslog-release
  version: latest

stemcells:
- os: ubuntu-trusty
  alias: ubuntu
  version: latest

instance_groups:
- name: syslog_forwarder
  jobs: 
  - name: syslog_forwarder
    release: syslog-release
  instances: 1
  stemcell: ubuntu
  azs: [z1]
  vm_type: default
  networks:
  - name: default

- name: syslog_storer
  jobs: 
  - name: syslog_storer
    release: syslog-release
    properties:
      port: 24173
      transport: relp
  instances: 1
  stemcell: ubuntu
  azs: [z1]
  vm_type: default
  persistent_disk_type: default
  networks:
  - name: default

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
