golang-1.25-linux/1e4dadb8a796a20044e177a108eec65780cd59c308da84f7fdbfdbc758cdf312:
  size: 66768540
  object_id: 6c76ac72-8881-4c92-7c4f-f95ce2409740
  sha: sha256:aac1b08a0fb0c4e0a7c1555beb7b59180b05dfc5a3d62e40e9de90cd42f88235
golang-1.25-linux/8cbbeb9a25df0cd15038235e0504a02ae6a1badd0b923d46d99a9db1654704a9:
  size: 59660846
  object_id: 65cbbe70-6250-4987-6858-54b1dc84f61a
  sha: sha256:7716a0d940a0f6ae8e1f3b3f4f36299dc53e31b16840dbd171254312c41ca12e
golang-1.25-linux/288cfe8883218087eeb75040802f471670df0e64e5c4d360b68b0109830b9329:
  size: 59766306
  object_id: e475a5eb-4a07-40c6-524d-4becfb618ba6
  sha: sha256:d7fa7f8fbd16263aa2501d681b11f972a5fd8e811f7b10cb9b26d031a3d7454b
golang-1.25-windows/117efdd98cac4d6d362504cddfb6e0926852569d5dd7330479e26c5477b5ada0:
  size: 74815266
  object_id: 01e5edcf-8f4b-4d76-68c1-28b390ace470
  sha: sha256:9bbe0fc64236b2b51f6255c05c4232532b8ecc0e6d2e00950bd3021d8a4d07d4
golang-1.25-windows/d59b40b0d4a5b7f3359d943bcd143637163db0351db4038ba7a1a490a0a6fbec:
  size: 67442664
  object_id: a740b2d1-dcff-41ff-5cb9-0ecd0443845e
  sha: sha256:ae756cce1cb80c819b4fe01b0353807178f532211b47f72d7fa77949de054ebb
golang-1.25-windows/fdc6f89451567c145ae473d9dee3b4828cb3c741829125604e98d8e37bbfe51f:
  size: 67419304
  object_id: 62e93c31-fe0e-4970-67dd-93840c7cbf54
  sha: sha256:4a974de310e7ee1d523d2fcedb114ba5fa75408c98eb3652023e55ccf3fa7cab
